### ISSUE TITLE
i2c bus

### ISSUE THREAD

**Issue by gambrose** [qiuchengxuan/bmp280#1]
Am I right in thinking that as it stands it is not possible to use this lib with a BMP280 connected to an i2c bus?

I am fairly new to rust but from looking over the code I think I would need to implement an `I2cBus` that implemented the Bus trait.

I am happy to try and put together a PR but wanted to reach out first as I might need some help, guidance as this is my first embedded rust project.

**Comment by qiuchengxuan** [comment]
> Am I right in thinking that as it stands it is not possible to use this lib with a BMP280 connected to an i2c bus?
> 
> I am fairly new to rust but from looking over the code I think I would need to implement an `I2cBus` that implemented the Bus trait.
> 
> I am happy to try and put together a PR but wanted to reach out first as I might need some help, guidance as this is my first embedded rust project.

Exactly right.
I don't have a BMP280 with I2C so only SPI implemented for now.
PR are welcomed :-D

**Comment by gambrose** [comment]
Created #2
